CREATE TABLE [dbo].[CAT_CATEGORIA] (
    [CAT_INT_ID]   UNIQUEIDENTIFIER NOT NULL,
    [CAT_NOMBRE]   VARCHAR (50)     NOT NULL,
    [CAT_SYS_NAME] VARCHAR (50)     NOT NULL,
    [CAT_STATUS]   BIT              NULL,
    CONSTRAINT [PK_CAT_CATEGORIA] PRIMARY KEY CLUSTERED ([CAT_INT_ID] ASC)
);

