CREATE TABLE [dbo].[TBL_FACTURA] (
    [FAC_INT_ID]    UNIQUEIDENTIFIER CONSTRAINT [DF_TBL_FACTURA_FAC_INT_ID] DEFAULT (newid()) NOT NULL,
    [FAC_NUMBER]    VARCHAR (50)     NULL,
    [PAG_INT_ID]    UNIQUEIDENTIFIER NULL,
    [FAC_FECHA]     DATETIME         NULL,
    [USE_INT_ID]    UNIQUEIDENTIFIER NULL,
    [FAC_SUB_TOTAL] DECIMAL (18, 2)  NULL,
    [FAC_DESCUENTO] DECIMAL (18, 2)  NULL,
    [FAC_IVA]       DECIMAL (18, 2)  NULL,
    [FAC_TOTAL]     DECIMAL (18, 2)  NULL,
    CONSTRAINT [PK_TBL_FACTURA] PRIMARY KEY CLUSTERED ([FAC_INT_ID] ASC),
    CONSTRAINT [FK_TBL_FACTURA_CAT_PAGO] FOREIGN KEY ([PAG_INT_ID]) REFERENCES [dbo].[CAT_PAGO] ([PAG_INT_ID]),
    CONSTRAINT [FK_TBL_FACTURA_TBL_USER] FOREIGN KEY ([USE_INT_ID]) REFERENCES [dbo].[TBL_USER] ([USE_INT_ID])
);



