CREATE TABLE [dbo].[TBL_TEM_PEDI] (
    [TEM_INT_ID]       UNIQUEIDENTIFIER  DEFAULT (newid()) NOT NULL,
	[TEM_USER_LOGIN]   VARCHAR(100) NOT NULL,
    [TEM_PRODUC]       UNIQUEIDENTIFIER NOT NULL,
    [TEM_CANT]		   INT				NOT NULL,
    [TEM_PRECIO]	   DECIMAL (18, 2)  NOT NULL,
    [TEM_FECHA]		   DATETIME         NOT NULL
);