-- =============================================
-- Author:		<Author,,Jeanneth Mota>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_IM_USER_INFO] (
    @USE_INF_INT_ID UNIQUEIDENTIFIER ,
	@CAT_TYP_USER   UNIQUEIDENTIFIER,
    @USE_INF_PRIMER_N   VARCHAR(100),
	@USE_INF_SEGUNDO_N  VARCHAR(100),
	@USE_INF_PRIMER_A   VARCHAR(50),
	@USE_INF_SEGUNDO_A  VARCHAR(50),
	@USE_INF_FECHA_NAC  DATE,
	@USE_INF_CED        VARCHAR(50),
	@USE_INF_TEL        VARCHAR(50),
	@USE_INF_EMAIL      VARCHAR(100),
	@USE_LOGIN			VARCHAR(100)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

   BEGIN TRANSACTION

    BEGIN TRY

	  IF NOT EXISTS (SELECT * FROM TBL_USER_INFO WHERE USE_INF_INT_ID = @USE_INF_INT_ID)
	  BEGIN

	  IF (@CAT_TYP_USER = CAST(CAST( 0 AS BINARY) AS UNIQUEIDENTIFIER))
	  BEGIN
		SET @CAT_TYP_USER = NULL
	  END

			INSERT INTO [dbo].[TBL_USER_INFO]
             (
				    [USE_INF_INT_ID]
				   ,[CAT_TYP_USER]
				   ,[USE_INF_PRIMER_N]
				   ,[USE_INF_SEGUNDO_N]
				   ,[USE_INF_PRIMER_A]
				   ,[USE_INF_SEGUNDO_A]
				   ,[USE_INF_FECHA_NAC]
				   ,[USE_INF_CED]
				   ,[USE_INF_TEL]
				   ,[USE_INF_EMAIL]
		       )
			 VALUES
			   (
					@USE_INF_INT_ID,
					@CAT_TYP_USER,
					@USE_INF_PRIMER_N,
					@USE_INF_SEGUNDO_N,
					@USE_INF_PRIMER_A,
					@USE_INF_SEGUNDO_A,
					@USE_INF_FECHA_NAC,
					@USE_INF_CED,
					@USE_INF_TEL,
					@USE_INF_EMAIL
			   )
		UPDATE TBL_USER SET USE_INF_INT_ID = @USE_INF_INT_ID
		WHERE USE_LOGIN = @USE_LOGIN
		END
        ELSE
		   BEGIN
				UPDATE TBL_USER_INFO
				SET CAT_TYP_USER = @CAT_TYP_USER,
					USE_INF_PRIMER_N = @USE_INF_PRIMER_N,
					USE_INF_SEGUNDO_N = @USE_INF_SEGUNDO_N,
					USE_INF_PRIMER_A = @USE_INF_PRIMER_A,
					USE_INF_SEGUNDO_A = @USE_INF_SEGUNDO_A,
					USE_INF_FECHA_NAC = @USE_INF_FECHA_NAC,
					USE_INF_CED = @USE_INF_CED,
					USE_INF_TEL = @USE_INF_TEL,
					USE_INF_EMAIL = @USE_INF_EMAIL
			  WHERE USE_INF_INT_ID = @USE_INF_INT_ID

		  END

   COMMIT TRANSACTION

   END TRY
   BEGIN CATCH
        ROLLBACK TRANSACTION 

    END CATCH
END